version: '3.8'

services:

  postgres-darwini:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USER=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=darwini-core
    volumes:
      - pg_data:/bitnami/postgresql

volumes:
  pg_data:
